CREATE TABLE "categories" (
    "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50) UNIQUE NOT NULL
);
CREATE TABLE "products" (
    "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50) UNIQUE NOT NULL,
    "stock_quantity" integer NOT NULL DEFAULT 0,
    "price" decimal(10, 2) NOT NULL DEFAULT 0,
    "category_id" integer,
    "supplier_id" integer NOT NULL,
    CONSTRAINT "chk_positive_price" CHECK (price >= 0),
    CONSTRAINT "chk_positive_stock" CHECK (stock_quantity >= 0)
);
CREATE TABLE "suppliers" (
    "supplier_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50) UNIQUE NOT NULL,
    "contact_person_firstname" varchar(50),
    "contact_person_secondname" varchar(50),
    "email" varchar(150),
    "phonenumber" varchar(12) NOT NULL,
    "country" varchar(60),
    CONSTRAINT "chk_email_has_at" CHECK (email LIKE '%@%')
);
ALTER TABLE "products"
ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "products"
ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id") ON DELETE
SET NULL ON UPDATE CASCADE;